services:
  postgres:
      image: postgres:latest
      ports:
        - "5432:5432"
      volumes:
        - ./postgres:/var/lib/postgres
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: mamba-project
      networks:
        - mynetwork
networks:
  mynetwork:
    driver: bridge